# =============================================================================
# dbt Profile for de_template
# =============================================================================
# Uses DuckDB with iceberg and httpfs extensions to read Iceberg tables
# from MinIO (local) or cloud object storage.
#
# Credentials are read from environment variables (injected by docker-compose).
# For local MinIO: set explicit values in env/local.env.
# For cloud: either set env vars or rely on your platform credential chain.
#
# DUCKDB_S3_ENDPOINT must NOT have http:// prefix (DuckDB httpfs format).
# For MinIO: minio:9000  |  For AWS S3: s3.amazonaws.com
# =============================================================================

de_pipeline:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /dbt/de_pipeline.duckdb
      schema: main
      threads: 4
      extensions:
        - httpfs
        - parquet
        - iceberg
      settings:
        memory_limit: "2GB"
        s3_endpoint: "{{ env_var('DUCKDB_S3_ENDPOINT') }}"
        # Empty-string fallback is intentional: cloud profiles (AWS IAM, GCS
        # Workload Identity, Azure Managed Identity) leave these vars unset and
        # rely on the platform credential chain. MinIO (local) sets them explicitly.
        s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID', '') }}"
        s3_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY', '') }}"
        s3_url_style: "path"
        s3_use_ssl: "{{ env_var('DUCKDB_S3_USE_SSL') }}"
        s3_region: "{{ env_var('AWS_REGION') }}"
        unsafe_enable_version_guessing: "{{ env_var('DUCKDB_UNSAFE_ENABLE_VERSION_GUESSING') }}"
