-- =============================================================================
-- dbt/models/staging/stg_taxi.sql
-- Generated by: make scaffold DATASET=taxi
-- =============================================================================
-- Passthrough staging model: reads from Silver Iceberg via iceberg_scan(),
-- applies minimal column aliases, and filters nulls on the event timestamp.
--
-- Update dbt/models/sources/sources.yml to point at your Silver path.
-- =============================================================================

with source as (
    select * from {{ source('raw_taxi', 'cleaned_taxi') }}
),

renamed as (
    select
        -- Surrogate key
        taxi_id,

        -- Timestamps and partition
        pickup_datetime,
        dropoff_datetime,
        pickup_date,

        -- Measures and dimensions
        vendor_id,
        passenger_count,
        trip_distance_miles,
        rate_code_id,
        store_and_fwd_flag,
        pickup_location_id,
        dropoff_location_id,
        payment_type_id,
        fare_amount,
        extra_amount,
        mta_tax,
        tip_amount,
        tolls_amount,
        improvement_surcharge,
        total_amount,
        congestion_surcharge,
        airport_fee,

        -- Metadata
        ingestion_ts

    from source
    where pickup_datetime is not null
)

select * from renamed
